#!/usr/bin/env node

// Build script: reads PNG logo files and generates src/logos.ts with Uint8Array exports
// Run with: node scripts/encode-logos.js

const fs = require("fs");
const path = require("path");

const LOGO_BASE = path.resolve(__dirname, "../../../drivzu/logo/png");

const LOGOS = [
  {
    name: "MOTION_COMBO",
    file: path.join(LOGO_BASE, "motion-combo/drivzu-motion-combo-480.png"),
    description: "Primary brand mark (480px)",
  },
  {
    name: "WORDMARK",
    file: path.join(LOGO_BASE, "wordmark/drivzu-wordmark-480.png"),
    description: "Text-only logo (480px)",
  },
  {
    name: "MONOGRAM",
    file: path.join(LOGO_BASE, "app-icons/drivzu-monogram-180.png"),
    description: "Compact monogram icon (180px)",
  },
];

const OUTPUT = path.resolve(__dirname, "../src/logos.ts");

function encodeLogo(filePath) {
  if (!fs.existsSync(filePath)) {
    console.error(`  WARNING: Logo not found: ${filePath}`);
    return null;
  }
  const buffer = fs.readFileSync(filePath);
  const bytes = Array.from(new Uint8Array(buffer));
  return bytes;
}

function generateTypeScript() {
  const lines = [
    "// Auto-generated by scripts/encode-logos.js — DO NOT EDIT",
    "// Contains base64-encoded logo data as Uint8Arrays for Figma image creation",
    "",
  ];

  for (const logo of LOGOS) {
    console.log(`  Encoding ${logo.name}: ${logo.file}`);
    const bytes = encodeLogo(logo.file);
    if (!bytes) {
      lines.push(`// ${logo.name}: file not found at build time`);
      lines.push(`export const ${logo.name}_BYTES: Uint8Array = new Uint8Array([]);`);
      lines.push("");
      continue;
    }

    const size = bytes.length;
    console.log(`    → ${size} bytes (${(size / 1024).toFixed(1)} KB)`);

    // Split into chunks of 80 numbers per line for readability
    const CHUNK_SIZE = 40;
    const chunks = [];
    for (let i = 0; i < bytes.length; i += CHUNK_SIZE) {
      chunks.push(bytes.slice(i, i + CHUNK_SIZE).join(","));
    }

    lines.push(`/** ${logo.description} — ${(size / 1024).toFixed(1)} KB */`);
    lines.push(`export const ${logo.name}_BYTES: Uint8Array = new Uint8Array([`);
    for (const chunk of chunks) {
      lines.push(`  ${chunk},`);
    }
    lines.push(`]);`);
    lines.push("");
  }

  return lines.join("\n");
}

console.log("Encoding Drivzu logos...");
const output = generateTypeScript();
fs.writeFileSync(OUTPUT, output, "utf8");
console.log(`\nGenerated: ${OUTPUT}`);
console.log(`File size: ${(fs.statSync(OUTPUT).size / 1024).toFixed(1)} KB`);
